#!/usr/bin/env python3
"""Generate HTML report from summary."""

import json
import os
from pathlib import Path


GITHUB_PAGES_URL = os.environ.get("GITHUB_PAGES_URL", "https://example.github.io/daily-reports")


def load_summary() -> dict:
    """Load summary data."""
    with open("summary.json", "r", encoding="utf-8") as f:
        return json.load(f)


def render_announcements(announcements: list) -> str:
    """Render announcements section."""
    if not announcements:
        return '<p class="empty">本周无公告</p>'
    
    items = "\n".join(
        f'<li><a href="{a["link"]}">{a["subject"]}</a></li>'
        for a in announcements
    )
    return f"<ul>{items}</ul>"


def render_votes(votes: list) -> str:
    """Render votes section."""
    if not votes:
        return '<p class="empty">本周无投票</p>'
    
    html_parts = []
    for vote in votes:
        has_objection = vote.get("has_objection", False)
        css_class = "vote-item has-objection" if has_objection else "vote-item"
        
        status_html = ""
        if has_objection:
            status_html = '<span class="status warning">⚠️ 有异议</span>'
        else:
            status_html = '<span class="status passed">✅ 已通过</span>'
        
        objection_html = ""
        if has_objection and vote.get("objection_summary"):
            objection_html = f'<p class="objection">{vote["objection_summary"]}</p>'
        
        html_parts.append(f'''
        <article class="{css_class}">
            <h3><a href="{vote["link"]}">{vote["subject"]}</a></h3>
            {status_html}
            {objection_html}
        </article>''')
    
    return "\n".join(html_parts)


def render_discussions(discussions: list) -> str:
    """Render discussions section."""
    if not discussions:
        return '<p class="empty">本周无讨论</p>'
    
    html_parts = []
    for disc in discussions:
        llm_summary = disc.get("llm_summary", {})
        summary = llm_summary.get("summary", "")
        key_points = llm_summary.get("key_points", [])
        conclusion = llm_summary.get("conclusion", "")
        
        key_points_html = ""
        if key_points:
            points = "\n".join(
                f'<p><strong>@{p.get("author", "")}:</strong> {p.get("point", "")}</p>'
                for p in key_points
            )
            key_points_html = f'<div class="key-points">{points}</div>'
        
        conclusion_html = ""
        if conclusion:
            conclusion_html = f'<p class="conclusion">{conclusion}</p>'
        
        html_parts.append(f'''
        <article class="discussion-item">
            <h3><a href="{disc["link"]}">{disc["subject"]}</a></h3>
            <p class="meta">{disc.get("reply_count", 0)} 条回复 · {len(disc.get("participants", []))} 位参与者</p>
            <p class="summary">{summary}</p>
            {key_points_html}
            {conclusion_html}
        </article>''')
    
    return "\n".join(html_parts)


def render_jira(jira_count: int, jira_summary: str) -> str:
    """Render JIRA section."""
    return f'''
    <p>本周新建 <strong>{jira_count}</strong> 个 Issue</p>
    <div class="jira-summary">
        <p>{jira_summary}</p>
    </div>'''


def generate_html(summary: dict) -> str:
    """Generate full HTML report."""
    week = summary.get("week", "")
    date_range = summary.get("date_range", {})
    start = date_range.get("start", "")
    end = date_range.get("end", "")
    
    return f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flink 社区周报 | {week}</title>
    <link rel="stylesheet" href="../assets/style.css">
</head>
<body>
    <div class="container">
        <header>
            <h1>Flink 社区周报 | {week}</h1>
            <p class="date-range">{start} ~ {end}</p>
        </header>

        <section class="announcements">
            <h2>📢 公告</h2>
            {render_announcements(summary.get("announcements", []))}
        </section>

        <section class="votes">
            <h2>🗳️ 投票</h2>
            {render_votes(summary.get("votes", []))}
        </section>

        <section class="discussions">
            <h2>💬 讨论</h2>
            {render_discussions(summary.get("discussions", []))}
        </section>

        <section class="jira">
            <h2>🎫 JIRA</h2>
            {render_jira(summary.get("jira_count", 0), summary.get("jira_summary", ""))}
        </section>

        <footer>
            <p>Generated by Flink Weekly Report System</p>
        </footer>
    </div>
</body>
</html>'''


def update_index(week: str):
    """Update index.html with report list."""
    reports_dir = Path("docs/flink-dev/reports")
    reports_dir.mkdir(parents=True, exist_ok=True)
    
    # Get all reports
    reports = sorted([f.stem for f in reports_dir.glob("*.html")], reverse=True)
    
    # Group by year
    years = {}
    for w in reports:
        year = w.split("-W")[0]
        if year not in years:
            years[year] = []
        years[year].append(w)
    
    # Generate HTML
    sections = ""
    for year, weeks in sorted(years.items(), reverse=True):
        items = "".join(f'<li><a href="reports/{w}.html">{w}</a></li>' for w in sorted(weeks, reverse=True))
        sections += f'<section class="month"><h2>📅 {year}</h2><ul>{items}</ul></section>'
    
    html = f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flink 社区周报</title>
    <link rel="stylesheet" href="assets/style.css">
</head>
<body>
    <div class="container">
        <header>
            <h1>Flink 社区周报</h1>
            <p>Apache Flink dev 邮件列表周报归档</p>
        </header>
        {sections if sections else '<p>暂无报告</p>'}
    </div>
</body>
</html>'''
    
    with open("docs/flink-dev/index.html", "w", encoding="utf-8") as f:
        f.write(html)
    print("Index updated: docs/flink-dev/index.html")


def main():
    """Main entry point."""
    summary = load_summary()
    week = summary.get("week", "")
    
    # Generate HTML
    html = generate_html(summary)
    
    # Save report
    output_dir = Path("docs/flink-dev/reports")
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{week}.html"
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"Report saved to {output_path}")
    
    # Update index
    update_index(week)


if __name__ == "__main__":
    main()
