#!/usr/bin/env python3
"""Generate HTML report and DingTalk message from GitHub activity data."""

import json
import os
from datetime import datetime
from pathlib import Path

REPO = "apache/fluss"
REPO_NAME = "Fluss"
GITHUB_PAGES_URL = os.environ.get("GITHUB_PAGES_URL", "https://your-username.github.io/daily-reports")


def load_json(filepath: str) -> dict:
    """Load JSON file."""
    with open(filepath, 'r', encoding='utf-8') as f:
        return json.load(f)


def save_json(data: dict, filepath: str):
    """Save data as JSON file."""
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def generate_critical_section(critical_issues: list) -> str:
    """Generate critical issues section."""
    if not critical_issues:
        return '<p class="no-issues">✅ 今日无重大问题</p>'
    return '<ul class="critical-list">' + ''.join(f'<li>{issue}</li>' for issue in critical_issues) + '</ul>'


def generate_item_list(items: list, item_type: str) -> str:
    """Generate HTML list for issues or PRs."""
    if not items:
        return '<p class="empty">暂无</p>'
    
    html_items = []
    for item in items:
        number = item.get('number', '')
        title = item.get('title', '')
        url = item.get('url', '')
        author = item.get('author', {})
        if isinstance(author, dict):
            author = author.get('login', 'unknown')
        elif not author:
            author = 'unknown'
        labels = ', '.join(l.get('name', '') for l in item.get('labels', []) if isinstance(l, dict))
        
        label_html = f'<span class="labels">{labels}</span>' if labels else ''
        html_items.append(f'<li><a href="{url}">#{number}</a> {title} <span class="author">@{author}</span> {label_html}</li>')
    
    return '<ul>' + ''.join(html_items) + '</ul>'


def generate_html_report(raw_data: dict, summary: dict, output_path: str):
    """Generate full HTML report."""
    date = raw_data['date']
    
    html = f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>🌊 {REPO_NAME} 每日动态 - {date}</title>
    <link rel="stylesheet" href="../assets/style.css">
</head>
<body>
    <div class="container">
        <header>
            <h1>🌊 {REPO_NAME} 每日动态</h1>
            <p class="date">📅 {date}</p>
            <p class="repo">🔗 <a href="https://github.com/{REPO}">{REPO}</a></p>
        </header>
        
        <section class="stats">
            <div class="stat">📝 {len(raw_data.get('new_issues', []))} 新 Issues</div>
            <div class="stat">✅ {len(raw_data.get('closed_issues', []))} 关闭</div>
            <div class="stat">✨ {len(raw_data.get('open_prs', []))} 新 PRs</div>
            <div class="stat">🎉 {len(raw_data.get('merged_prs', []))} 合并</div>
        </section>
        
        <section class="highlights">
            <h2>🔥 核心要点</h2>
            <ul>
                {"".join(f'<li>{h}</li>' for h in summary.get('highlights', ['暂无']))}
            </ul>
        </section>
        
        <section class="critical">
            <h2>⚠️ 重点关注</h2>
            {generate_critical_section(summary.get('critical_issues', []))}
        </section>
        
        <section class="new-items">
            <h2>📝 新建 Issue/PR</h2>
            <h3>Issues</h3>
            {generate_item_list(raw_data.get('new_issues', []), 'issue')}
            <h3>Pull Requests</h3>
            {generate_item_list(raw_data.get('open_prs', []), 'pr')}
        </section>
        
        <section class="activity">
            <h2>💬 Issue/PR 动态</h2>
            <h3>Issue 讨论</h3>
            <p>{summary.get('issue_comments_summary', '今日无新评论')}</p>
            <h3>PR Review</h3>
            <p>{summary.get('pr_review_summary', '今日无新 Review 评论')}</p>
        </section>
        
        <section class="closed">
            <h2>✅ 关闭 Issue/PR</h2>
            <h3>已关闭 Issues</h3>
            {generate_item_list(raw_data.get('closed_issues', []), 'issue')}
            <h3>已合并 PRs</h3>
            {generate_item_list(raw_data.get('merged_prs', []), 'pr')}
        </section>
        
        <footer>
            <p>Generated by <a href="https://github.com/{REPO}">daily-reports</a></p>
        </footer>
    </div>
</body>
</html>'''
    
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html)
    print(f"HTML report saved to {output_path}")


def generate_dingtalk_message(raw_data: dict, summary: dict, report_url: str) -> dict:
    """Generate DingTalk webhook message."""
    date = raw_data['date']
    
    stats = f"📊 **统计**: {len(raw_data.get('new_issues', []))} 新 Issues | {len(raw_data.get('closed_issues', []))} 关闭 | {len(raw_data.get('open_prs', []))} 新 PR | {len(raw_data.get('merged_prs', []))} 合并"
    
    highlights = summary.get('highlights', [])
    highlights_text = '\n'.join(f'- {h}' for h in highlights[:5]) if highlights else '- 今日暂无重要更新'
    
    critical = summary.get('critical_issues', [])
    critical_text = '\n'.join(f'- {c}' for c in critical) if critical else '无'
    
    markdown_content = f"""## 🌊 Fluss 每日动态 ({date})

{stats}

🔥 **核心要点**:
{highlights_text}

⚠️ **需要关注**: 
{critical_text}

🔗 [查看完整报告]({report_url})"""

    return {
        "msgtype": "markdown",
        "markdown": {
            "title": f"Fluss 每日动态 ({date})",
            "text": markdown_content
        }
    }


def update_index_html():
    """Update the archive index page."""
    reports_dir = Path('docs/reports')
    reports_dir.mkdir(parents=True, exist_ok=True)
    
    # Get all report files
    report_files = sorted(reports_dir.glob('*.html'), reverse=True)
    
    # Group by month
    months = {}
    for f in report_files:
        date_str = f.stem  # YYYY-MM-DD
        month = date_str[:7]  # YYYY-MM
        if month not in months:
            months[month] = []
        months[month].append(date_str)
    
    # Generate HTML
    sections = []
    for month, dates in sorted(months.items(), reverse=True):
        items = ''.join(f'<li><a href="reports/{d}.html">{d}</a></li>' for d in sorted(dates, reverse=True))
        sections.append(f'''
        <section class="month">
            <h2>📅 {month}</h2>
            <ul>{items}</ul>
        </section>''')
    
    html = f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>🌊 Fluss Daily Reports</title>
    <link rel="stylesheet" href="assets/style.css">
</head>
<body>
    <div class="container">
        <header>
            <h1>🌊 Fluss Daily Reports</h1>
            <p>apache/fluss 每日动态归档</p>
        </header>
        {"".join(sections) if sections else '<p>暂无报告</p>'}
    </div>
</body>
</html>'''
    
    with open('docs/index.html', 'w', encoding='utf-8') as f:
        f.write(html)
    print("Index updated: docs/index.html")


def main():
    """Main entry point."""
    # Load data
    raw_data = load_json('raw_data.json')
    summary = load_json('summary.json')
    
    date = raw_data['date']
    
    # Generate HTML report
    html_path = f'docs/reports/{date}.html'
    generate_html_report(raw_data, summary, html_path)
    
    # Generate DingTalk message
    report_url = f"{GITHUB_PAGES_URL}/reports/{date}.html"
    dingtalk_msg = generate_dingtalk_message(raw_data, summary, report_url)
    save_json(dingtalk_msg, 'dingtalk_message.json')
    print("DingTalk message saved to dingtalk_message.json")
    
    # Update index.html
    update_index_html()


if __name__ == '__main__':
    main()
